version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: pipelineiq-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: pipelineiq-grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pipelineiq
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./docker/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus
    restart: unless-stopped
